backend:
  name: github
  repo: atapas/gatsby-all-in-one
media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: _data/blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
