backend:
  name: github
  repo: atapas/gatsby-all-in-one
  branch: master
  base_url: https://api.netlify.com
  auth_endpoint: auth
media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: _data/blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Featured Image
        name: cover
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
      - label: Category (Upload Image only for New Category)
        name: category 
        widget: "object"
        required: true
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Image", name: "image", widget: "image", required: false}
        options: ["Business", "Covid19", "Life", "Technology", "Vernacular"]
      - label: Tags
        name: tags
        widget: list
      - label: Featured
        name: featured
        widget: boolean
        required: false
